minr-dev/desktop

.github/workflows/release.yml, electron-builder.yml, electron.vite.config.ts, package-lock.json, package.json, src/main/env.d.ts, src/main/index.ts, src/main/services/DataSource.ts, src/main/services/GoogleAuthServiceImpl.ts, src/main/updater.ts, src/renderer/src/App.tsx
=> feat: パッケージ配布のための調整

electron-builder.yml
=> fix: electron-builderの設定を修正

src/main/index.ts
=> feat: #53 多重起動しないように修正

src/main/services/SpeakEventNotifyProcessorImpl.ts
=> fix: #65 予定の音声通知の時間差が効いていない不具合を修正

src/main/services/GoogleAuthServiceImpl.ts, src/renderer/index.html, src/renderer/src/components/timeTable/EventSlot.tsx, src/renderer/src/components/timeTable/TimeLane.tsx, src/renderer/src/components/timeTable/TimeTable.tsx
=> 短いイベントの表示がズレる不具合の修正 

electron.vite.config.ts, src/renderer/src/App.tsx, src/renderer/src/components/DrawerAppBar.tsx, src/renderer/src/components/UserContext.tsx, src/renderer/src/components/UserProvider.tsx, src/renderer/src/components/timeTable/common.ts, src/renderer/src/main.tsx, src/renderer/src/pages/PreferencePage.tsx, src/shared/dto/UserPreference.ts
=> ダークモードとライトモードの切替ができるように対応 

src/main/services/WindowWatcher.ts, src/renderer/src/App.tsx, src/renderer/src/components/timeTable/TimeTable.tsx, src/renderer/src/hooks/useActivityEvents.ts, src/renderer/src/inversify.config.ts, src/renderer/src/services/EventTimeCell.ts, src/renderer/src/services/ISpeakEventService.ts, src/renderer/src/services/SpeakEventServiceImpl.ts, src/renderer/src/types.ts, src/shared/constants.ts
=> アクティビティの表示更新処理をサブスクライブ方式に変更 

src/renderer/src/components/settings/AccountSetting.tsx, src/shared/data/UserPreference.ts
=> feat: #88 openaiのapiキーを設定項目に追加

src/renderer/src/components/category/CategoryEdit.tsx, src/renderer/src/components/category/CategoryList.tsx, src/renderer/src/components/category/CategoryPulldownComponent.tsx, src/renderer/src/components/common/fields/TextColorPickerField.tsx, src/renderer/src/components/crud/CRUDList.tsx, src/renderer/src/components/label/LabelEdit.tsx, src/renderer/src/components/label/LabelList.tsx, src/renderer/src/components/label/LabelMultiSelectComponent.tsx, src/renderer/src/components/project/ProjectEdit.tsx, src/renderer/src/components/project/ProjectList.tsx, src/renderer/src/components/project/ProjectPulldownComponent.tsx, src/renderer/src/components/timeTable/EventEntryForm.tsx, src/renderer/src/components/timeTable/TimeTable.tsx, src/renderer/src/hooks/useFetchCRUDData.ts, src/renderer/src/services/CategoryProxyImpl.ts, src/renderer/src/services/ICRUDProxy.ts, src/renderer/src/services/ICategoryProxy.ts, src/renderer/src/services/ILabelProxy.ts, src/renderer/src/services/IProjectProxy.ts, src/renderer/src/services/LabelProxyImpl.ts, src/renderer/src/services/ProjectProxyImpl.ts, src/shared/data/EventEntry.ts
=> イベントにプロジェクトとカテゴリー、ラベルを設定できるようにする

src/renderer/src/components/settings/AccountSetting.tsx, src/renderer/src/components/settings/GeneralSetting.tsx, src/renderer/src/components/settings/GoogleCalendarSetting.tsx, src/renderer/src/hooks/useAppSnackbar.tsx
=> feat: #84 アプリ共通のSnackbarを作成

src/renderer/src/components/timeTable/EventSlot.tsx
=> fix: #110 リサイズとD&Dがスムーズになるように修正

package-lock.json, package.json, src/renderer/src/components/timeTable/ActivityTimeline.tsx, src/renderer/src/components/timeTable/EventEntryForm.tsx
=> feat: #63 作業実績の編集画面でアクティビティが参照できるように対応

package-lock.json, package.json, src/main/services/EventEntryServiceImpl.ts, src/main/services/WindowLogServiceImpl.ts, src/renderer/src/components/category/CategoryEdit.tsx, src/renderer/src/components/common/form/FormContainer.tsx, src/renderer/src/components/crud/CRUDFormDialog.tsx, src/renderer/src/components/label/LabelEdit.tsx, src/renderer/src/components/project/ProjectEdit.tsx, src/renderer/src/components/timeTable/EventEntryForm.tsx, src/renderer/src/hooks/useEventEntries.ts
#112
- イベントに開始・終了日時を選択するピッカーを追加
- イベントの日時がタイムテーブルの外側に変更された場合の処理を追加
- 1日の境界付近でのイベント取得方法の修正
- Dialog内にformがある場合のスクロールに関するバグの修正
=> feat: 予定と実績のイベント編集で日付を変更する

src/renderer/src/components/timeTable/ActivitySlot.tsx, src/renderer/src/components/timeTable/EventSlot.tsx, src/renderer/src/components/timeTable/TimeLane.tsx, src/renderer/src/components/timeTable/TimeTable.tsx
#131
- nullチェックの方法を変更し、0がnull扱いにならないように修正
=> fix: 1日の開始時刻を0時にするとタイムテーブルが表示されない

package-lock.json, package.json, src/main/inversify.config.ts, src/main/ipc/ActivityUsageServiceHandlerImpl.ts, src/main/services/ActicityUsageServiceImpl.ts, src/main/services/ActivityColorServiceImpl.ts, src/main/services/IActivityUsageService.ts, src/main/services/__tests__/ActivityColorServiceImpl.test.ts, src/main/services/__tests__/ActivityUsageServiceImpl.test.ts, src/main/types.ts, src/renderer/src/App.tsx, src/renderer/src/components/DrawerAppBar.tsx, src/renderer/src/components/activityUsage/ActivityGraph.tsx, src/renderer/src/components/menu.ts, src/renderer/src/hooks/useActivityUsage.ts, src/renderer/src/inversify.config.ts, src/renderer/src/pages/ActivityUsagePage.tsx, src/renderer/src/services/ActivityUsageProxyImpl.ts, src/renderer/src/services/IActivityUsageProxy.ts, src/renderer/src/types.ts, src/shared/constants.ts, src/shared/data/ActivityUsage.ts, src/shared/data/__tests__/ActivityUsageFixture.ts
#87 #62
- 指定した期間のアプリの使用時間をグラフ表示するページを実装
- 実績として登録した作業に作業分類を設けて、分類別の作業時間を集計表示する
=> feat: アクティビティのTOP5を表示する

src/main/inversify.main.config.ts, src/main/ipc/AutoRegisterActualServiceHandlerImpl.ts, src/main/ipc/PlanAutoRegistrationServiceHandlerImpl.ts, src/main/services/EventAggregationServiceImpl.ts, src/main/services/EventEntryServiceImpl.ts, src/main/services/IEventAggregationService.ts, src/main/services/IEventEntryService.ts, src/main/services/IFreeTimeSlotService.ts, src/main/services/IPlanAutoRegistrationService.ts, src/main/services/IPlanAvailableTimeSlotService.ts, src/main/services/ITaskAllocationService.ts, src/main/services/ITaskService.ts, src/main/services/PlanAutoRegistrationServiceImpl.ts, src/main/services/PlanAvailableTimeSlotService.ts, src/main/services/TaskAllocationServiceImpl.ts, src/main/services/TaskServiceImpl.ts, src/main/services/__tests__/EventAggregationServiceImpl.test.ts, src/main/services/__tests__/PlanAvailableTimeSlotServiceImpl.test.ts, src/main/services/__tests__/TaskAllocationServiceImpl.test.ts, src/main/services/__tests__/__mocks__/EventAggregationServiceMockBuilder.ts, src/main/services/__tests__/__mocks__/EventEntryServiceMockBuilder.ts, src/main/services/__tests__/__mocks__/TaskServiceMockBuilder.ts, src/main/types.ts, src/shared/constants.ts, src/shared/data/OverrunTask.ts, src/shared/data/PlanAutoRegistrationResult.ts, src/shared/data/TaskAllocation.ts, src/shared/data/TaskAllocationResult.ts, src/shared/data/__tests__/OverrunTaskFixture.ts
#159 
- タスクから予定を自動登録する機能の追加
- 追記予定
=> feat: #172 タスクから予定を自動作成する 自動登録処理(mainプロセス)

src/main/services/ActualPredictiveCreationServiceImpl.ts
#218
- パターンにアプリ名が指定されていないときのパターンマッチを修正
=> fix: 機能テストバグ対応 - 実績の自動登録の修正

src/main/services/CalendarSyncProcessorImpl.ts
#207 
テスト課題表 20
#181 
- 「Google Calenderと同期する」設定がオフになっているとき、定期実行される同期処理を行わないように修正
=> fix: 機能テストバグ対応 - Google同期設定の無効化時に自動同期される不具合の修正

package.json, src/main/services/__tests__/CalendarSynchronizerImpl.test.ts, src/renderer/src/components/project/ProjectDropdownComponent.tsx, src/renderer/src/components/task/TaskDropdownComponent.tsx, src/renderer/src/components/task/TaskEdit.tsx, src/renderer/src/hooks/useTaskMap.ts
機能テストの再実施後に確認したバグを対応したのでそのマージを行う。
`lint`や`typecheck`などのチェックをgithubで行い問題ないことを確認する。
=> fix: 機能テスト課題表対応ブランチのマージ

.github/workflows/release.yml
#258 
- Linux版がリリースされる要因となっている箇所をコメントアウト
=> fix: Linux版のリリースが作られている

src/main/services/GitHubOrganizationStoreService.ts, src/main/services/GitHubProjectV2ItemStoreService.ts, src/main/services/GitHubProjectV2StoreService.ts, src/main/services/IGitHubOrganizationStoreService.ts, src/main/services/IGitHubProjectV2ItemStoreService.ts, src/main/services/IGitHubProjectV2StoreService.ts
=> feat: GitHubのプロジェクトおよびタスク、Issueの同期-DAO

src/main/inversify.main.config.ts, src/main/ipc/PlanTemplateApplicationServiceHandlerImpl.ts, src/main/ipc/PlanTemplateEventHandlerImpl.ts, src/main/ipc/PlanTemplateHandlerImpl.ts, src/main/services/IPlanTemplateApplicationService.ts, src/main/services/IPlanTemplateEventService.ts, src/main/services/IPlanTemplateService.ts, src/main/services/PlanTemplateEventServiceImpl.ts, src/main/services/PlanTemplateServiceImpl.ts, src/main/types.ts, src/renderer/src/components/planTemplate/PlanTemplateEdit.tsx, src/renderer/src/services/IPlanTemplateApplicationProxy.ts, src/renderer/src/services/IPlanTemplateEventProxy.ts, src/renderer/src/services/IPlanTemplateProxy.ts, src/renderer/src/types.ts, src/shared/constants.ts, src/shared/data/PlanTemplate.ts, src/shared/data/PlanTemplateEvent.ts
=> feat: 予定のテンプレート機能-DAO実装

src/main/ipc/PlanTemplateApplicationServiceHandlerImpl.ts, src/main/ipc/PlanTemplateEventHandlerImpl.ts, src/main/ipc/PlanTemplateHandlerImpl.ts, src/main/services/IPlanTemplateApplicationService.ts, src/main/services/IPlanTemplateEventService.ts, src/main/services/IPlanTemplateService.ts, src/main/types.ts, src/renderer/src/components/planTemplate/PlanTemplateEdit.tsx, src/renderer/src/components/planTemplate/PlanTemplateList.tsx, src/renderer/src/hooks/cacheKey.ts, src/renderer/src/hooks/usePatternMap.ts, src/renderer/src/hooks/usePlanPatternMap.ts, src/renderer/src/hooks/usePlanTemplateMap.ts, src/renderer/src/hooks/usePlanTemplatePage.ts, src/renderer/src/inversify.renderer.config.ts, src/renderer/src/pages/SettingPage.tsx, src/renderer/src/services/CategoryProxyImpl.ts, src/renderer/src/services/IPlanTemplateApplicationProxy.ts, src/renderer/src/services/IPlanTemplateEventProxy.ts, src/renderer/src/services/IPlanTemplateProxy.ts, src/renderer/src/services/LabelProxyImpl.ts, src/renderer/src/services/PatternProxyImpl.ts, src/renderer/src/services/PlanPatternProxyImpl.ts, src/renderer/src/services/PlanTemplateProxyImpl.ts, src/renderer/src/services/ProjectProxyImpl.ts, src/renderer/src/services/TaskProxyImpl.ts, src/renderer/src/types.ts, src/shared/constants.ts, src/shared/data/PlanTemplate.ts, src/shared/data/PlanTemplateEvent.ts
#295 
- 予定テンプレートの設定画面を追加
- 設定タブのスクロールを有効化
- 根本的な解決ではないので、別タスクで整理したい → #299
=> 予定のテンプレート機能-テンプレート一覧実装

package-lock.json, package.json, src/main/services/EventEntryServiceImpl.ts, src/renderer/src/hooks/useAutoRegistrationPlan.ts
リリースビルドの作成のため、テスト課題対応後のブランチをdevelopにマージする。
=> release: テスト課題対応ブランチの取り込み

src/main/index.ts, src/main/services/IpcService.ts
#318 
- windowが閉じられているときにIpc通信をしないようにする
- 復帰時のwindow生成を修正
=> fix: macで、MINRを起動したままスリープしたあと復帰した際にエラーになる

.github/workflows/release.yml, package-lock.json, package.json
#205 
署名プロセスにAzure Signing Toolでの署名プロセスを追加(Windowsのみ)
=> feat: Windows版にコード署名を行う-実装

src/renderer/src/components/project/ProjectList.tsx
プロジェクトの一覧にて、GitHubプロジェクトの項目が無かったので追加しました。
=> fix: GITHUBプロジェクトの表示項目を追加

src/renderer/src/components/settings/GeneralSetting.tsx, src/renderer/src/components/timeTable/ActivitySlot.tsx
#352 
* 作業開始時間が正しい形式であるかを判定し、正しくない場合は警告を表示する
* 休憩時間の入力チェックを行い以下の条件に合う場合は警告を表示する
* 正しい形式ではない
* 終了時刻が開始時刻より前に設定されている
=> fix: 設定(一般)の時刻設定の入力チェックを修正する

src/renderer/src/components/common/form/NotificationSettingsFormControl.tsx, src/renderer/src/components/planTemplate/PlanTemplateEventForm.tsx, src/renderer/src/components/settings/GeneralSetting.tsx, src/renderer/src/components/settings/PomodoroSetting.tsx, src/renderer/src/components/timeTable/EventEntryForm.tsx
=> fix: 読み上げ時間の最低値を修正する

src/renderer/src/components/task/TaskDropdownComponent.tsx
#343 
プロジェクト更新したときのタスクドロップダウンが空になるように修正
=> fix: タスクが選択された状態でプロジェクトを変更した際にタスクが解除されない
