minr-dev/desktop

src/main/services/GitHubEventStoreServiceImpl.ts
src/main/services/GitHubSyncProcessorImpl.ts
src/main/services/IGitHubEventStoreService.ts

Issue: #76
既存の登録確認を、日付を指定して既存のデータを読み込んで、比較するようにしていたが、
既存のテストデータの問題か、あるいは、GitHubのイベントの日付の仕様がよくわかっていなくて、
正しい実装になっていないため、IDを指定して既存のデータを検索して比較するように修正。

fix: #76 GitHubイベントの取り込みで一意性制約違反にならないように修正

---

src/main/index.ts
src/main/inversify.config.ts
src/main/services/CalendarSyncProcessorImpl.ts
src/main/services/WindowWatchProcessorImpl.ts
src/main/services/__tests__/CalendarSynchronizerImpl.test.ts
src/main/types.ts
src/renderer/src/components/timeTable/TimeTable.tsx
src/shared/constants.ts

Issue: #48
イベントの表示はもともとポーリング方式ではなくイベントの登録更新のタイミングで
最新データの取り直しが行われていたので、サブスクライブするのは、Googleカレンダーで
更新されたデータがあったときだけでよかった。

feat: #48 Googleカレンダー同期によるイベント更新をサブスクライブする

---

src/renderer/src/components/timeTable/EventSlot.tsx

Issue: #93 
drag時点の座標とdrop時点の座標が完全一致するときだけclickイベント判定していたが、
座標が 5 ピクセル以内で一致するという条件に変更。

fix: #93 drag&dropとclickの判定方法を修正

---

src/renderer/src/components/timeTable/TimeTable.tsx
src/renderer/src/hooks/useEventEntries.ts

予定と実績が混ざって計算されていたため、それぞれをfilterしてから
計算するように修正

fix: #96 同時間帯のイベント表示のサイズ計算の不具合を修正

---

src/main/ipc/EventEntryServiceHandlerImpl.ts
src/main/services/CalendarSyncProcessorImpl.ts
src/main/services/EventEntryFactory.ts
src/main/services/EventEntryServiceImpl.ts
src/main/services/IEventEntryService.ts
src/main/services/__tests__/__mocks__/EventEntryServiceMockBuilder.ts
src/renderer/src/components/timeTable/ActivitySlot.tsx
src/renderer/src/components/timeTable/EventSlot.tsx
src/renderer/src/services/OverlapEventServiceImpl.ts
src/renderer/src/services/__tests__/OverlapEventServiceImpl.test.ts
src/shared/utils/StrUtil.ts

Issue: #95 
Issueのエントリー内容は「登録していない実績が登録されている」ということなのだが、
D&Dの不具合が修正されたことで、その現象は、再現しなくなってしまったが、
サービス層にバリデーションが実装されていなかった不具合だけ対応した。
また、Google風のカレンダー表示を数段階で実装追加しているのだが、その段階で、
縦横の座標計算がバラバラのえuseEffectで実装されていて、うまく連動していなかったので、
1つの useEffect に実装して、座標計算の処理を1つにまとめて、重なり具合の不具合も修正した。

D&Dで異常なデータ登録がなくなるように修正

---

src/renderer/src/components/category/CategoryList.tsx
src/renderer/src/components/label/LabelList.tsx
src/renderer/src/components/project/ProjectList.tsx
src/renderer/src/pages/SettingPage.tsx

Issue: #102 
- UUIDで採番されているIDを一覧で見ても、役に立たないし、id と name がそれぞれユニーク制約にしてあるので、idの表示列は不要
- 設定画面の「作業区分」をカテゴリーに変更（他のところではカテゴリーと表示しているので）

refactor: #102 CRUDの一覧表示からIDの列を削除

---

src/renderer/src/components/label/LabelMultiSelectComponent.tsx

イベントの新規登録のときには、ラベルがブランクなので、undefinedの場合には、
`[]` で初期化するように修正。

fix: #105 Selectのmultipleのときの初期値を配列に修正

---

package-lock.json
package.json
src/renderer/src/components/timeTable/ActivitySlot.tsx
src/renderer/src/components/timeTable/EventSlot.tsx
src/renderer/src/components/timeTable/EventSlotText.tsx
src/renderer/src/components/timeTable/TimeLane.tsx
src/renderer/src/components/timeTable/TimeTable.tsx
src/renderer/src/services/EventTimeCell.ts
src/renderer/src/utils/ColotUtil.ts

Issue: #114 
- 背景色の輝度からテキストカラーを選択
- イベントの枠線をテーマ色に合わせて切替
- イベントの最小枠高さを30分に変更

feat: #114 背景色とテキストカラーの配色を最適化

---

src/renderer/src/components/timeTable/ActivityTimeline.tsx
src/renderer/src/components/timeTable/EventEntryForm.tsx
src/renderer/src/services/EventTimeCell.ts

Issue: #122 
- 実績のダイアログにはアクティビティのタイムラインを常時表示する
- GitHubイベントとアクティビティを別々のタイムラインアイテムで実装
- GitHubイベントの表示を改良

feat: #122 アクティビティのタイムラインにGitHubイベントも表示

---

src/main/services/EventEntryServiceImpl.ts
src/main/services/WindowLogServiceImpl.ts
src/main/services/__tests__/EventEntryServiceImpl.test.ts
src/main/services/__tests__/WindowLogServiceImpl.test.ts
src/renderer/src/components/timeTable/ActivitySlot.tsx
src/renderer/src/components/timeTable/ActivityTableLane.tsx
src/renderer/src/components/timeTable/EventSlot.tsx
src/renderer/src/components/timeTable/TimeLane.tsx
src/renderer/src/components/timeTable/TimeTable.tsx
src/renderer/src/components/timeTable/common.ts
src/renderer/src/inversify.config.ts
src/renderer/src/types.ts

#66
- タイムテーブルの日付の初期値を1日の開始時刻にする
- タイムテーブルの日付をDIコンテナから取得
- イベント・アクティビティの取得方法を、取得期間と重なる時間があれば取得するように変更
- 1日の境界にあるイベント・アクティビティの高さの計算方法を修正
- イベント取得のテストの実装
- WindowLog取得のテストの実装
- ~イベント取得のテストが成功しない~
- ~テストではイベントが取得できていない(アプリケーションでは取得できて正しい表示になっている)~
- ~アクティビティ取得のテスト~

fix: 1日の境界にあるイベントの表示が正しくない

---

src/main/services/EventEntryServiceImpl.ts
src/main/services/UserPreferenceStoreServiceImpl.ts
src/main/services/WindowLogServiceImpl.ts
src/main/services/__tests__/EventEntryServiceImpl.test.ts
src/main/services/__tests__/WindowLogServiceImpl.test.ts
src/renderer/src/components/settings/GeneralSetting.tsx
src/renderer/src/components/timeTable/ActivitySlot.tsx
src/renderer/src/components/timeTable/EventEntryForm.tsx
src/renderer/src/components/timeTable/EventSlot.tsx
src/renderer/src/components/timeTable/TimeLane.tsx
src/renderer/src/components/timeTable/TimeTable.tsx
src/renderer/src/components/timeTable/common.ts
src/renderer/src/hooks/useActivityEvents.ts
src/renderer/src/hooks/useEventEntries.ts
src/shared/data/UserPreference.ts
src/shared/data/__tests__/UserPreferenceFixture.ts

#79 
- 設定画面で1日の開始時間が設定できるよう修正
- タイムラインが設定した開始時間から表示されるよう修正
- 設定した開始時間によってはタイムラインのイベント表示が1日分ずれてしまう
- 例えば、2/15 18:00 にイベントを作成した後に、1日の開始時間を23時に設定すると、翌日 18:00 のイベントのように表示されてしまう
- テスト

feat: #79 1日の開始時間を設定可能にする

---

src/renderer/src/components/category/CategoryList.tsx
src/renderer/src/components/label/LabelList.tsx
src/renderer/src/components/project/ProjectList.tsx

#150 
* 不具合対応
* 不具合原因
* 設定でのラベル追加・編集では、データの追加、編集、削除時にサーバーのデータを更新していますが、アプリのデータを最新化する`refetch`を実行していませんでした。そのため、アプリ内のデータが最新版に更新されていないことから、ラベルが即時反映されていませんでした。
* 対応内容
* 設定からラベルデータを更新する際に、`refetch`を実行するように修正しました。
* 参考コード
* [タイムラインのラベル追加処理のrefetch](https://github.com/minr-dev/desktop/blob/develop/src/renderer/src/components/label/LabelMultiSelectComponent.tsx#L76)
* [タイムラインのカテゴリー追加処理のrefetch](https://github.com/minr-dev/desktop/blob/develop/src/renderer/src/components/category/CategoryDropdownComponent.tsx#L67)
* [タイムラインのプロジェクト追加処理のrefetch](https://github.com/minr-dev/desktop/blob/develop/src/renderer/src/components/project/ProjectDropdownComponent.tsx#L69)
* 本対応で関連する処理についてコメントを追加

fix: 設定で追加したラベルがタイムラインに即時反映されない

---

src/renderer/src/components/common/fields/TextColorPickerField.tsx

#151  
* 不具合対応
* 不具合原因
* `TextColorPickerField.tsx`の`handleChangeComplete`にて色が変更された際に`anchorEl`をnullにすることでカラーパレットを閉じていました。カラーパレットは色を即時反映させるため、少し色を変えるだけで`anchorEl`がnullになり画面が閉じられることが不具合の原因でした。
* 対応内容
* 色が変更された際に`anchorEl`をnullにする処理を削除することで、パレットが閉じられないようにしました。
* カラーパレットは画面外をクリックすることで閉じるため、閉じれないといった問題は発生しません。
* 参考webサイト
* [Reactでカラーピッカーの導入](https://engineer-blog.ajike.co.jp/react_color_picker/)

fix: 設定からラベルのカラーパレットをドラッグすると画面が表示されなくなる

---

src/main/inversify.config.ts
src/main/ipc/ApplicationHandlerImpl.ts
src/main/ipc/EventEntryServiceHandlerImpl.ts
src/main/services/ApplicationServiceImpl.ts
src/main/services/EventEntryFactory.ts
src/main/services/IApplicationService.ts
src/main/types.ts
src/renderer/src/components/application/ApplicationEdit.tsx
src/renderer/src/components/application/ApplicationList.tsx
src/renderer/src/components/timeTable/ActivityTimeline.tsx
src/renderer/src/components/timeTable/EventEntryForm.tsx
src/renderer/src/components/timeTable/EventSlotText.tsx
src/renderer/src/components/timeTable/TimeTable.tsx
src/renderer/src/hooks/useApplicationMap.ts
src/renderer/src/hooks/useApplicationPage.ts
src/renderer/src/hooks/useEventEntries.ts
src/renderer/src/inversify.config.ts
src/renderer/src/pages/SettingPage.tsx
src/renderer/src/services/ApplicationProxyImpl.ts
src/renderer/src/services/AutoRegisterActuralService.ts
src/renderer/src/services/EventEntryProxyImpl.ts
src/renderer/src/services/IApplicationProxy.ts
src/renderer/src/services/IAutoRegisterActualService.ts
src/renderer/src/services/IEventEntryProxy.ts
src/renderer/src/types.ts
src/shared/constants.ts
src/shared/data/Application.ts
src/shared/data/EventEntry.ts
src/shared/data/__tests__/EventEntryFixture.ts
src/shared/utils/TimeUtil.ts

#89  
* 実績の自動登録機能
* タイムテーブルに「実績の自動登録」ボタンを追加
* これを押すことでタイムテーブル上に仮登録状態の実績が表示される
* 仮登録状態の実績は通常の実績のようにタイムテーブル上で編集可能(ただしDBへの保存はされない)
* 「仮実績の本登録」ボタンを押すことでDBへ保存される
* 設定ページに「アプリ」を追加
* 実績の自動登録時に参照する、アプリケーションと、プロジェクト・カテゴリー・ラベルの紐づけを設定する
* アクティビティから実績のタイトルをつける
* アクティビティのウィンドウタイトル毎に紐づけ方を設定できるようにする
* タイムテーブルの日付を変えても仮登録の実績が保持されるようにする
* 過去の実績とアクティビティの履歴から紐づけを自動的に設定する

feat: アクティビティから自動的に作業を分類する

---

src/main/env.d.ts
src/main/inversify.config.ts
src/main/ipc/GitHubAuthServiceHandlerImpl.ts
src/main/services/GitHubAuthServiceImpl.ts
src/main/services/IDeviceFlowAuthService.ts
src/renderer/src/components/settings/AccountSetting.tsx
src/renderer/src/hooks/useGitHubAuth.ts
src/renderer/src/services/GitHubAuthProxyImpl.ts
src/renderer/src/services/IDeviceFlowAuthProxy.ts
src/shared/constants.ts

#170 
- server側にあった認証処理の一部をdesktopへ移動(GitHub)
- デバイスフロー方式による認証の実装(GitHub)
- openid-clientを利用して実装しているが、GitHubの仕様によりそのままではポーリング処理が正しく動作しなかったため、独自実装になっている部分がある。
- GitHubの仕様は以下を参考にしている。
- https://docs.github.com/ja/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps#device-flow
- 認証方式の変更に伴い、renderer側の表示も変更している。
- ユーザーコードの表示
- 「コードを入力する」ボタンの追加

feat: #170 OAuth認証をPKCEにする GitHub認証の対応

---

jest.config.node.js
src/__tests__/jest.electron.ts
src/main/services/WinstonLoggerImpl.ts
src/main/services/__tests__/ActivityServiceImpl.test.ts
src/main/services/__tests__/ActivityUsageServiceImpl.test.ts
src/main/services/__tests__/CalendarSynchronizerImpl.test.ts
src/main/services/__tests__/TestDataSource.ts

#188 
ユニットテストを実行した際に、`getPath`のライブラリが認識できず、ログ出力のパス作成でエラーが出力されている不具合を確認したので、エラーが出力されないように修正を行う。
* Context
*  今回のエラーは、`electron` のライブラリが認識されていない状態で呼び出されることが原因。
* `jest` では `electron` は通常動作しないことからエラーが発生していると考えられる。
* Decision
* `getPath`のライブラリが認識できない場合は、`process.cwd()`でログ出力のパスを作成する。
* Consequences
* ユニットテストにおいて、動作しないなどのモジュールはモック化するのが一般的だが、ロガーによるログ出力をテストでも活用することを想定しているため、モック化はできない。
* ロガーの本来の機能を維持したまま、`getPath`でエラーが発生しないように修正する必要がある。
* `getPath`のエラーは`electron`ライブラリを認識できないことから発生しているため、 `process.versions.electron`で`electron`の状態を確認することでエラーがでるか判定することができる、
* `process.versions.electron`で`electron`ライブラリが使用できない場合は、現在の作業ディレクトリを返す`process.cwd()`を使用しログが出力されるようにすることでエラーなくログ出力を行える。
* Context
* 現在のユニットテストは、`console.log`を使用しており記録に残らない課題がある。
* 今回のエラー対応と合わせて、試験的にユニットテストのログをログファイルに出力する。
* Decision
* …

fix: #188 テスト時にloggerでgetPathを呼び出すとエラーになる

---

.env.example
.github/workflows/release.yml
electron-builder.yml
electron.vite.config.ts
package-lock.json
package.json
src/main/services/GoogleAuthServiceImpl.ts

#177 
- ワークフローの修正
- matrixの利用
- releaseの作成ライブラリを`softprops/action-gh-release`に変更
- コード署名と公証のプロセスの実装
- Windows以外はコメントアウト
- 動作しなかったり、動作確認できなかったりするため
- Google認証時のエラーのログ出力
- 認証中のエラーをrendererに伝える
- OS毎の起動
- Mac arm64版はインストールまではいけるが、起動時に署名の問題でエラーがでる
- Mac x64版も同様
- Windows版はインストール時に警告はでるが、インストール後は普通に起動できる
- 証明書を入れれば解消する見込み
- linux版はリリースまではできているが、動作確認をできていない
- 認証(Windows版で確認)
- Google認証、GitHub認証ともに動作する
- ただし、Googleは正規の方法でクライアントIDを発行していない
- デスクトップアプリなのにユニバーサルWindowsプラットフォーム(UWP)を指定している
- クライアントシークレットの埋め込みを回避するため
- https://github.com/minr-dev/desktop/issues/170#issuecomment-2436683623
- Googleの推奨ではないので、再検討の必要あり
- https://developers.google.com/identity/protocols/oauth2?hl=ja#installed

fix: #177 Releaseがmac用のバイナリだけになっている

---

src/renderer/src/components/timeTable/EventEntryForm.tsx

#212 
* Context
* 予定と実績は日時が無いと成立しないため、日時設定が必ず必要になる。
* 予実の追加・編集にて日付が無い場合は保存できないように処理を実装する必要がある。
* Decision
* 日付フォームの`validate`に、日時が有効であるかの判定処理を追加して対応する。
* Consequences
* 開始日などの日付フォームには`required`が設定されているが、日付フォームを空にすると自動的に日時と判定できないデータが入力されてしまう。
* データを入力されてしまうと空ではないため、日付の型が正しいか別途判定を行う必要がある。

fix: 機能テストバグ対応 - 予実追加の日付フォームが空の場合の警告処理が機能していない

---

src/renderer/src/components/timeTable/EventEntryForm.tsx

#214 
* Context
* 入力エラーが発生した場合は対象のフォームが強調表示され、ヘルパーテキストが表示される仕様となっている。
* 日時の入力エラー時に強調表示がされていないため修正する必要がある。
* Decision
* `Picker`に`slotProps`の`textField`を追加し、入力エラーの強調表示を実装する。
* Consequences
* `DatePicker`、`TimePicker`では`slotProps`の`textField`にてテキストフォームと同様のエラー表示ができる。
* 修正箇所が重複するため、マージ先は修正関連するブランチとする。

fix: 機能テストバグ対応 - 予実追加のvalidateで返される警告が画面に反映されていない

---

src/renderer/src/components/task/TaskEdit.tsx

#225 
* Context
* タスクの追加ではタスクがプロジェクトと必ず紐づいているため、プロジェクトの選択は必須となっている。
* タスク追加・編集ではプロジェクトが選択されているときに保存を実行する。
* Decision
* `プロジェクトなし(NULL)`に対して`validate`を追加し入力エラーを表示されるようにする。
* Consequences
* タスク追加・編集のプロジェクトにて`プロジェクトなし`が選択されているときにNULLの文字が入っているため、`required`が機能していなかった。
* `プロジェクトなし`が選択されているときの文字列を判定し`validate`を設定する必要がある。
* テスト課題表2の修正も併せて実施

fix: 機能テストバグ対応 - タスク追加・編集でプロジェクトが未選択のまま保存できてしまう

---

src/renderer/src/components/common/form/NotificationSettingsFormControl.tsx

#224 
* Context
* フォーム入力にエラーがある場合は、入力エラーの表示をする必要がある。
* Decision
* 通知タイミングの`Textfield`に`error`の項目を追加する。
* Consequences
* ポモドーロタイマー設定の`Textfield`を確認したところ、入力エラーの表示に必要な`error`が抜けていた。

fix: 機能テストバグ対応 - ポモドーロタイマー設定の入力エラー表示が機能していない

---

src/renderer/src/components/common/fields/TextColorPickerField.tsx

#232 
* Context
* 入力フォームはデザインを`outlined`で統一している。
* フォームに入力した際は、そのフォームが何なのかわかるようにタイトルが常に見えている状態にする。
* Decision
* `shrink`を追加し、`value`が入っている場合は常に縮小するように修正する。
* Consequences
* `InputLabelProps`の`shrink`では`label`を常に縮小する設定を行うことができる。
* `shrink`に`value`の入力判定を記載することで、外部からの入力でもタイトルを縮小することができる。

fix: 機能テストバグ対応 - カラーの選択時にタイトルと入力した値が重なってしまう

---

src/main/ipc/TaskHandlerImpl.ts
src/main/services/ITaskService.ts
src/main/services/TaskServiceImpl.ts
src/renderer/src/components/pattern/PatternEdit.tsx
src/renderer/src/components/project/ProjectDropdownComponent.tsx
src/renderer/src/components/task/TaskDropdownComponent.tsx
src/renderer/src/components/timeTable/EventEntryForm.tsx
src/renderer/src/hooks/useTaskMap.ts
src/renderer/src/services/ITaskProxy.ts
src/renderer/src/services/TaskProxyImpl.ts
src/shared/data/Task.ts

#238 
* Context
* プロジェクトのドロップダウンが未入力時にテキスト内に入力されている状態のため修正する。
* Decision
* プロジェクトのドロップダウンにてNULLを空文字に変更する。
* `Task`の`list`にてプロジェクトのフィルター有りと、無しの切り替え機能を追加する。
* Consequences
* プロジェクトのドロップダウンにて`プロジェクトなし`を選択したときに`NULL`の文字が入っていたのがテキスト入力の原因。
* `NULL`を削除すれば表示は他のドロップダウンと同様になる。
* `Task`の一覧取得には`list`を使用しているが、ドロップダウンも同じく使用しているため、空文字だとプロジェクト未選択時のタスクのドロップダウンで全件が出力されてしまう。
* タスクのドロップダウンではプロジェクト未選択時にタスクは表示しない仕様。
* プロジェクトでのフィルターの有無を別途引数で選択するように実装し、空文字でもフィルター有りの検索を行えるように修正する。

fix: 機能テストバグ対応 - プロジェクトなしを選択した際にフォームの表示が異なる

---

src/renderer/src/components/project/ProjectDropdownComponent.tsx
src/renderer/src/components/task/TaskDropdownComponent.tsx
src/renderer/src/components/task/TaskEdit.tsx

#240 
* Context
* 各フォームからのタスク新規追加はタスクドロップダウンを経由してタスク追加に遷移している。
* ドロップダウンからタスク追加に遷移する際にプロジェクトを固定値にする。
* Decision
* タスク追加・編集にプロジェクトIDの引数を追加し、プロジェクトの有無で固定値にするかを判定する処理を追加する。
* Consequences
* 各フォームからのタスク新規追加はタスクドロップダウンを経由してタスク追加に遷移している。
* `projectId`の有無で、タスク一覧からの完全新規かドロップダウンからのプロジェクト指定新規か判別することができる。
* タスク追加ではプロジェクトの指定をドロップダウンで行っているが、プロジェクトドロップダウンを修正すると規模が大きくなるため、タスク追加の中にプロジェクトの固定値の処理を追加する。

fix: 機能テストバグ対応 - ドロップダウンからタスクを追加時にプロジェクトIDを固定値にする

---

src/renderer/src/components/category/CategoryEdit.tsx
src/renderer/src/components/crud/CRUDFormDialog.tsx
src/renderer/src/components/label/LabelEdit.tsx
src/renderer/src/components/pattern/PatternEdit.tsx
src/renderer/src/components/project/ProjectEdit.tsx
src/renderer/src/components/settings/SettingFormBox.tsx
src/renderer/src/components/task/TaskEdit.tsx
src/renderer/src/components/timeTable/EventEntryForm.tsx
src/renderer/src/hooks/useFormManager.ts

#207 
テスト課題表 22~24
#169
- ダイアログが2重に開いているとき、アクティブなダイアログだけ保存処理が行われるように修正

fix: 機能テストバグ対応 - フォームの保存処理が伝播してしまう不具合の修正

---

src/main/services/EventAggregationServiceImpl.ts
src/main/services/TaskAllocationServiceImpl.ts
src/main/services/TaskServiceImpl.ts
src/main/services/UserPreferenceStoreServiceImpl.ts

#220 #221
- 予定の自動登録の際、期限日のあるタスクがないタスクより優先させるよう修正
- 予定の自動登録の際、予定登録済みなどで時間帯が2つにわかれた場合、早い方の時間帯から予定を登録するよう修正
- 登録済みの予定工数の計算で、論理削除された予定が計算対象に含まれてしまう不具合を修正
- 休憩時間のデフォルト値を修正

fix: 機能テストバグ対応 - 予定の自動登録の不具合の修正

---

src/main/inversify.main.config.ts
src/main/services/EventAggregationServiceImpl.ts
src/main/services/ITaskAllocationService.ts
src/main/services/ITaskProviderService.ts
src/main/services/PlanAutoRegistrationServiceImpl.ts
src/main/services/TaskAllocationServiceImpl.ts
src/main/services/TaskProviderServiceImpl.ts
src/main/services/TaskServiceImpl.ts
src/main/services/UserPreferenceStoreServiceImpl.ts
src/main/services/__tests__/TaskAllocationServiceImpl.test.ts
src/main/types.ts

#223 
- 予定自動登録を行う際、その日の予定に登録済みのタスクは、自動登録対象から外すようにする
- 自動登録対象のタスクを抽出する処理を別クラスに分離

fix: 機能テストバグ対応 - 工数の再設定フォームの表示条件の調整

---

src/renderer/src/components/timeTable/EventEntryForm.tsx
src/renderer/src/components/timeTable/TimeTable.tsx

#204 
- 仮登録状態のイベントの保存時に、DBにも保存するよう修正
- 仮登録状態のイベントの削除時に、DBからも削除するよう修正
- 仮登録状態のイベントをリサイズした時に、DBの時間も更新するよう修正
- 仮登録状態のイベントのドラッグ&ドロップした時に、DBの時間も更新するよう修正

fix: 仮登録状態のイベントの保存・削除処理を修正

---

src/main/ipc/GitHubAuthServiceHandlerImpl.ts
src/main/services/GitHubAuthServiceImpl.ts
src/main/services/IDeviceFlowAuthService.ts
src/renderer/src/components/settings/AccountSetting.tsx
src/renderer/src/hooks/useGitHubAuth.ts
src/renderer/src/services/GitHubAuthProxyImpl.ts
src/renderer/src/services/IDeviceFlowAuthProxy.ts
src/shared/constants.ts
src/shared/data/UserPreference.ts

#235 
- ポーリングの中断機能を実装
- コンポーネントのアンマウント時にポーリングを中断する
- ポーリングの待ち時間を調整
- openAiKeyの項目をコメントアウト

fix: 機能テストバグ対応 - GitHub認証のポーリング処理が二重に行えてしまう

---

src/main/ipc/GitHubAuthServiceHandlerImpl.ts
src/main/services/GitHubAuthServiceImpl.ts
src/main/services/IDeviceFlowAuthService.ts
src/main/services/OverlapEventMergeServiceImpl.ts
src/renderer/src/components/settings/AccountSetting.tsx
src/renderer/src/hooks/useGitHubAuth.ts
src/renderer/src/services/GitHubAuthProxyImpl.ts
src/renderer/src/services/IDeviceFlowAuthProxy.ts
src/shared/constants.ts
src/shared/data/UserPreference.ts

#234 
- ユーザーコード入力画面を表示する関数で、閉じたことを検出できるように変更
- ユーザーコードを開いたタイミングで「コードを入力する」ボタンを無効化し、閉じたタイミングで有効化する
- ログ出力の修正

fix: ユーザーコード入力画面を二重に開けないようにする

---

src/renderer/src/components/project/ProjectDropdownComponent.tsx
src/renderer/src/components/task/TaskEdit.tsx

#242 
* Context
* タスクの編集時に設定されているはずのプロジェクトが表示されないバグが発生。
* 編集時に初期値としてドロップダウンに設定されているプロジェクトを表示する必要がある。
* Decision
* fetchDataにプロジェクトIDを設定する処理を追加
* projectIdの有無で`projectId`固定値するかの分岐を追加
* Consequences
* 以前の修正でプロジェクトIDを検索したタスクからではなく、引数から`projectId`を取得するようにしたことが原因でバグが発生した。
* タスクの検索時に`projectId`を設定し、引数で`projectId`が設定されている場合は固定値として表示するように修正を行った。

fix: タスクの編集時にプロジェクトが表示されない

---

src/renderer/src/components/task/TaskDropdownComponent.tsx
src/renderer/src/hooks/useTaskMap.ts

#243 
* Context
* 予実の追加・編集からタスクを追加してそのタスクを選択するとタイムライン上で表示されないバグが発生した。
* 追加したタスクもタイムライン上で表示されるように修正を行う。
* Decision
* TaskDropDownにuseTaskMapのrefreshを追加
* Consequences
* タスクのマップはフィルターの有無で分かれており、それぞれ別々の条件で検索したタスクデータを保持している。
* タスクドロップダウンではフィルター有りのマップを使用している。
* タイムラインではフィルター無しのマップを使用しているため、タスクドロップダウンで追加したデータの更新が実行されていなかった。
* タスクドロップダウンでもフィルター無しのデータ更新を行うことで、タイムラインで表示されるように対応する。
* TODO: タイムラインとドロップダウンで別々の更新が必要ないように、タスクデータの更新処理を統合する
* useTaskMapで設定していたstaleTimeなどを他のマップと実装を揃えるため削除した。

fix: ドロップダウンからタスクを追加した際にタイムライン上で認識されない

---

src/main/services/PlanAutoRegistrationServiceImpl.ts
src/main/services/TaskAllocationServiceImpl.ts

#249 
- 追加工数が`0`の場合と`null`の場合を区別できるように修正
- 工数割り当てで`break`するときの条件を修正
- 配列から切り出したあともとに戻す動作を修正
- `push`だと後ろに追加されてしまい、順番が変わってしまっていた
- ログの追加

fix: 工数の再設定フォームで0時間を入力すると、超過していないタスクも登録されない

---

src/renderer/src/components/PomodoroTimerContextProvider.tsx
src/renderer/src/components/pomodoroTimer/PomodoroTimer.tsx
src/renderer/src/components/settings/PomodoroSetting.tsx

#247 
#251 
- ポモドーロタイマーの画面を開いたとき、タイマーが停止状態なら作業時間・休憩時間を現在の設定に合わせて更新する
- ポモドーロタイマーの設定で作業時間・休憩時間のバリデーションを1分以上にする
- セッション終了時、セッションの時間の設定が0秒だったら通知を送らない(念のため)

fix: ポモドーロタイマーの修正

---

src/main/services/EventNotifyProcessorImpl.ts
src/renderer/src/components/timeTable/EventEntryForm.tsx

#257 
- 削除された予定を音声読み上げ・デスクトップ通知の対象から除外する
- 仮予定を音声読み上げ・デスクトップ通知の対象から除外する
- 仮予定にリマインダーの設定を表示しない

fix: 予定の読み上げ関連の修正

---

src/main/services/CalendarSyncProcessorImpl.ts
src/renderer/src/components/timeTable/TimeTable.tsx

#253 #254 
- Googleカレンダーで作成→同期→MINRで編集→同期 の手順で変更内容が同期されるように修正
- Googleカレンダーとの同期対象から削除済みのイベントを除外する
- Googleカレンダーとの同期対象から仮状態のイベントを除外する
- ドキュメントの更新

fix: Googleカレンダー同期の修正

---

src/renderer/src/components/label/LabelMultiSelectComponent.tsx

#265 
- ラベル選択で新規ラベル追加時に空のラベルが登録される不具合の修正
- `Select`の仕様で、`MenuItem`以外のコンポーネントを押したときに`undefined`を選択した扱いになる
- MUIのGitHubでもIssueが作られており、進行中
- https://github.com/mui/material-ui/issues/26356
- 今回は、上記Issue内で示されていた現状できる対応のサンプルコードをもとに修正した
- https://codesandbox.io/p/sandbox/select-multi-with-close-button-j8to8
- かなり煩雑な実装なので、MUI側で機能改善されたらそれに合わせて修正したい
- `id`から見つからなかったラベルはラベル選択で`Chip`を表示しない
- イベントにラベル登録→設定(ラベル)でラベル削除、としたときに、イベントに消せない`Chip`が残ってしまうため

fix: イベント・パターンのラベル選択で新規ラベルを作成すると、空のラベルが登録される

---

src/renderer/src/components/DrawerAppBar.tsx
src/renderer/src/components/help/Help.tsx

#260 
* Context
* 設定からテーマが変更されたときに、ヘルプのダイアログも同じくテーマに合わせて変更される。
* Decision
* テーマの引数を追加し、ヘルプ内でテーマを色を適用するように修正を行った。
* Consequences
* App.tsxでは`Theme`を使用しているが、あらかじめ変数で宣言されている色データを適用している。
* ヘルプは`App`や`DrawAppBar`の`Theme`の適用外なので、他のテーマと色を合わせるために同様の変数をヘルプ内で宣言し使用する。
* バージョンが`0.1.4`に変更されたので適用する。

fix: ヘルプのダイアログにテーマが適用されない

---

src/renderer/src/components/task/TaskDropdownComponent.tsx

#266 
* Context
* ドロップダウンからタスクを追加した際に追加したタスクを選択する。
* タスクはプロジェクトと紐づいて登録されている必要がある。
* ドロップダウンからタスクを追加した際にプロジェクトが空の場合は何も選択されていない必要がある。
* Decision
* ~~プロジェクト未選択でタスクを登録した際は空文字を選択した状態にするように修正~~
* プロジェクトが未選択時は「プロジェクトを選択してください」とヘルプを表示するように修正
* Consequences
* ドロップダウンからタスクを追加した際に追加したタスクを選択する仕様になっていた。
* ~~プロジェクトが選択されていないときはタスクの選択も同様に何も選択されていない状態を返すように修正する。~~
* プロジェクトが未選択場合は紐づくプロジェクトが無いため、タスクは追加できない方がわかりやすい。

fix: ドロップダウンにてプロジェクトが無くても新規追加したタスクを登録できてしまう

---

src/renderer/src/components/task/TaskDropdownComponent.tsx

#263 
* Context
* 設定からタスクを追加時にタイムラインには即時反映されている必要がある。
* Decision
* タスクドロップダウンのuseEffectに更新処理を追加
* Consequences
* ドロップダウンからタスクを追加時は即時反映されていた
* タイムラインを開いた際に更新処理が行われていないので、ドロップダウンを開いた時に更新されるように修正を行う。
* `TaskDropdownComponent`の2つのuseEffectを1つに統合

fix: 設定(タスク)での更新が予実フォームのタスクドロップダウンに反映されない

---

package-lock.json
package.json
src/main/inversify.main.config.ts
src/main/ipc/AutoLaunchServiceHandlerImpl.ts
src/main/services/AutoLaunchServiceImpl.ts
src/main/services/IAutoLaunchService.ts
src/main/services/UserPreferenceStoreServiceImpl.ts
src/main/types.ts
src/renderer/src/components/settings/GeneralSetting.tsx
src/renderer/src/inversify.renderer.config.ts
src/renderer/src/services/AutoLaunchProxyImpl.ts
src/renderer/src/services/IAutoLaunchProxy.ts
src/renderer/src/types.ts
src/shared/constants.ts
src/shared/data/UserPreference.ts
src/shared/data/__tests__/UserPreferenceFixture.ts

#56 
#60 
- 設定(一般)に自動起動の設定を追加
- 自動起動を設定/解除する処理の追加
- 開発環境では自動起動の設定はしないようにする(正常に動作しないらしい)
- ユーザーがWindowsの設定でスタートアップを無効にすると、自動起動するにチェックがついていても起動しない
- この状態で自動起動をOFFにしても不整合は起きない
- `package.json`の`author`を会社名に変更
- プロパティの著作権のところが会社名になりました

feat: #56 OS起動時にアプリを自動起動する設定

---

.github/workflows/release.yml
electron-builder.yml
package-lock.json
package.json

#206 
- `asarUnpack`に`node_modules`の`.node`ファイルを追加
- これによりライブラリに署名がされ、署名の問題が解決する

fix: #206 Mac版でリリースができるようにする

---

src/main/ipc/PlanAutoRegistrationServiceHandlerImpl.ts
src/main/services/IPlanAutoRegistrationService.ts
src/main/services/ITaskProviderService.ts
src/main/services/PlanAutoRegistrationServiceImpl.ts
src/main/services/TaskProviderServiceImpl.ts
src/main/services/__tests__/TaskProviderServiceImpl.test.ts

#272 
* 予定の自動登録で割り当てるタスクを返すクラスの修正
* パラメータのprojectIdでタスクのフィルターを行うように修正
* ユニットテストを追加
* 仮予定の作成クラスの修正
* 要素名を指定してパラメータを渡すように修正
* →IPCハンドラーも同様に修正

feat: 予定の自動登録で、登録タスクのプロジェクトを指定できるようにする(mainプロセス)

---

src/main/ipc/PlanAutoRegistrationServiceHandlerImpl.ts
src/main/services/IPlanAutoRegistrationService.ts
src/main/services/ITaskProviderService.ts
src/main/services/PlanAutoRegistrationServiceImpl.ts
src/main/services/TaskProviderServiceImpl.ts
src/main/services/__tests__/TaskProviderServiceImpl.test.ts
src/renderer/src/components/timeTable/AutoRegisterProvisionalPlans.tsx
src/renderer/src/components/timeTable/AutoRegisterProvisionalPlansForm.tsx
src/renderer/src/components/timeTable/EventEntryForm.tsx
src/renderer/src/components/timeTable/TimeTable.tsx
src/renderer/src/hooks/useAutoRegistrationPlan.ts
src/renderer/src/services/IPlanAutoRegistrationProxy.ts
src/renderer/src/services/PlanAutoRegistrationProxy.ts

#272 
* 予定の自動登録のダイアログを追加
* タイムラインのボタンを押下したときにダイアログを表示するように修正
* プロジェクトを選択し、予定の自動登録を実行するように修正
* EventEntryformの軽微なエラーを修正

feat: 予定の自動登録で、登録タスクのプロジェクトを指定できるようにする(rendererプロセス)

---

src/main/services/WindowWatchProcessorImpl.ts

#316 
* スリープ時に実行するカレントデータの更新と初期化を修正
* WindowLogの更新処理を実行するように修正
* アクティビティの更新とカレントアクティビティの初期化を追加
* リファクタリング
* 使用していない変数を削除

fix: スリープ時にアクティビティが継続してしまう

---

src/main/services/GitHubTaskSyncServiceImpl.ts

fix: GitHub連携で予定工数の同期がされない不具合を修正

---

src/main/services/GitHubAuthServiceImpl.ts
src/renderer/src/components/settings/AccountSetting.tsx
src/renderer/src/hooks/useGitHubAuth.ts

#331 
#332 
- ユーザーコード入力画面を内部ブラウザではなく外部ブラウザで開くように変更
- 外部ブラウザは開いているかどうかの判定が難しいので、コードを入力するボタンの無効化制御を削除(二重に開けるようにする)
- ウィンドウが二重に開けるようになったことで、二重起動防止処理が不要になり結果的に#332のバグが解消

Release 1.0/bugfix/external device flow window

---

src/main/services/CalendarSyncProcessorImpl.ts

fix: MINRで削除されたイベントがGoogleカレンダーで消えない不具合の修正

---

src/renderer/src/components/timeTable/ActivitySlot.tsx
src/renderer/src/components/timeTable/ActivityTableLane.tsx
src/renderer/src/components/timeTable/TimeTable.tsx

#327 
* タイムラインのアクティビティがEVENT_ENTRY_NOTIFYのメッセージに合わせて更新されるように修正
今回の実装では時間の関係でbooleanで実装したが、将来的には親コンポーネントから実行し更新を行いたい

fix: タイムラインのアクティビティが即時反映されていない

---

src/main/services/IpcService.ts
src/main/services/__tests__/EventNotifyProcessorImpl.test.ts
src/main/services/__tests__/SpeakTimeNotifyProcessorImpl.test.ts
tsconfig.web.json

#338 
Dock格納時に、ウィンドウがない状態でIPC通信を送ってエラーになる。(厳密には、ウィンドウの存在チェックでエラーになる)
ウィンドウがないときは、IPC通信をしないかつエラーも起こさないように修正。
- tsconfigの修正は、開発環境のエラーの修正です。(本番には関係ないはずです)

fix: IPC通信時にWIndowがない場合はエラーを投げないように修正

---

src/renderer/src/components/timeTable/AutoRegisterProvisionalPlansForm.tsx

#340 
選択していないように見えて選択されている状態が問題なので、前のプロジェクトがデフォルトで選択されているように見えるように修正

fix: 予定の自動登録で、プロジェクトの初期値が表示されていない問題を修正

---

src/main/services/EventEntrySearchServiceImpl.ts
src/renderer/src/components/planAndActualCsv/PlanAndActualCsvOutput.tsx

#353 
- 共有のみフィルターを削除
- フィルターなしに実績が含まれるように修正
- 予定のみは、修正前のまま、全ての予定が含まれるようにする(共有のみを消したことでこの仕様の方がが明快になる)
- 1か月以上選択したときのエラーメッセージを、日数表示にして明確化

fix: 予実フィルターの変更とエラーメッセージの修正

---

src/renderer/src/components/timeTable/TimeTable.tsx

#347 
画面起動時の選択日時の初期設定と、今日ボタンを押したときの日時が同じになるように修正

fix: タイムテーブルの今日のボタンの日時設定を修正する

---

src/renderer/src/services/EventTimeCell.ts

#363 
IssueコメントイベントとPRレビューイベントに対する処理を追加
一部PRの番号がundefinedと表示されている不具合の修正

fix: GitHubアクティビティの内容表示を改善
